name: traintrack_lost_found
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  firebase_database: ^10.5.3
  flutter_keyboard_visibility: ^5.4.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.1
  dotted_border: ^2.1.0
  url_launcher: ^6.3.0
  cloudinary_public: ^0.13.0
  firebase_messaging: ^14.9.4
  http: ^0.13.5
  flutter_typeahead: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_logo.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/app_logo.png
    background_color: "#0A2A4D"
    theme_color: "#0A2A4D"
  windows:
    generate: true
    image_path: assets/app_logo.png
  macos:
    generate: true
    image_path: assets/app_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/app_logo.png